### ISSUE TITLE
make-your-game/history subject

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#1019]
make-your-game/history
---

[Try using the Dev Tool/Performance.](https://github.com/01-edu/public/blob/master/subjects/make-your-game/history/audit.md#is-there-no-frame-drop)
**Is there no frame drop?**

Possible answers:
1. Yes, there is no frame drop
2. No, there is no frame drop
Both answers mean exactly the same thing.

Question should be **Are there any frame drops?**

[Try using the Dev Tool/Performance.](https://github.com/01-edu/public/blob/master/subjects/make-your-game/history/audit.md#does-the-game-run-ator-around-60fps)
**Does the game run at/or around 60fps?**

What is considered around 60fps? Is 54fps still around 60?

**Comment by MSilva95** [comment]
In order to pass, the question should be validated as a yes.
If you reply "No" in the audits the audit will fail.
So we have to ask the question like that, and the NO will be the answer when you do have frame drops.
But i will change the question for better understanding thank you for the feedback!

**Comment by MSilva95** [comment]
Regarding the fps question, yes it from 50 or more, the question will be like this now:
```Does the game run at/or around 60fps?(from 50 to 60)```

**Comment by LEEDASILVA** [comment]
> I guess you mean [this Rendering tool in Chrome?](https://stackoverflow.com/questions/33292084/where-did-rendering-go-in-chrome-devtools/52960284#52960284)
> and I guess what you mean to ask Is the paint being used as little as practical?

when we say `and the option rendering with the pain ON, if possible` yes it is referring to the rendering of the paint with flashing green lights

but it can be also visible just by using the normal summary tab on the dev tool:

![image](https://user-images.githubusercontent.com/39002521/160108498-f08fd90e-4594-42e8-a40b-2eef27d76322.png)

you can see the `painting`. Notice that it is the lower one of them all.
so the question is just missing some good English ` Is the paint being used as little as possible?`

----

>Please clarify what do you mean by "layers being used the less possible"? Do you mean that the number of layers should be minimum? If the project uses only 1 layer, no layer promotion - is that a "yes"? Is usage of will-change: transform; mandatory in this task?

The question should be changed to `Are the layers being used as little as possible?`. Yes it should have a low number of layers.

The layers can cause performance issues, that's way we ask for the minimum number of layers as possible. So by creating a new layer you can remove the painting (always a tradeoff). if you add to much layers it will increase the composition and update tree so also causing performance issue.

So you must only promote the layer if you are going to use it. To remove painting so that it is used as little as possible you must add a layer, which uses `will-change: transform` so it is implied.

**Comment by jarmo-seljamaa** [comment]
Please clarify your last paragraph: "So you must only promote the layer if you are going to use it. To remove painting so that it is used as little as possible you must add a layer, which uses `will-change: transform` so it is implied."

Does this mean that using `will-change: transform` is required to pass? The project I'm auditing is not using it. The game runs on one single layer.

**Comment by LEEDASILVA** [comment]
You should promote elements that you plan to animate to their own layer (The best way to create a new layer is to use the `will-change`). So this means that the person that promotes the layer needs to use `will-change`.
 
If the person is using layers he should promote them, only if they are planing to animate that element.

Is this layer created and promoted because it is being animated?

**Comment by LEEDASILVA** [comment]
> Care must be taken not to create too many layers, however, as each layer requires both memory and management.
This also has to be considered
