### ISSUE TITLE
[SYSADMIN] - student session does not save software

### ISSUE THREAD

**Issue by sakenism** [01-edu/public#102]
**Describe the bug**
We have configured OS and flash drive as described in guide. Software that was installed during full ubuntu (not cut with scripts) is okay, but when we make a student session via flash drive, and install soft (google chrome) and reboot computer, soft is gone

**To Reproduce**
1. Install Google Chrome
2. Reboot

**Expected behavior**
Soft is supposed to be saved on each students' flash key
**Type**
Add the correct label to your bug report : blocking, major, minor

**Priority**
Normal

**Subject**
sysadmin

**Comment by xpetit** [comment]
In my opinion, the student should not have `id 0` access, so no `su`/`sudo`. The only way for him to install software is to put it in his `HOME` directory and without any `root` rights.
This is to avoid that they alter the system (install keylogger, change OS) which could cause problems since computers are shared between students.

Chromium is already installed so Chrome may not be necessary ?
