### ISSUE TITLE
recursivefactorial subject

### ISSUE THREAD

**Issue by freeworldwhoo** [01-edu/public#1024]
recursivefactorial
---
this exercise passes with iterative solution

**Comment by freeworldwhoo** [comment]
I did not test it but I think it is the same for iterativepower and recursivepower

**Comment by MSilva95** [comment]
For these I will probably add a restriction on using for loops.
So instead of this:
{ 'recursivpower','{"allowedFunctions":["--allow-builtin"]}'

it will become something like this:

'recursivepower','{"allowedFunctions":["--allow-builtin", "-no-for"]}'

For the iterative exercises i will have to find a way to restrict the recursive use

**Comment by MSilva95** [comment]
<https://github.com/01-edu/all/pull/1167>
