### ISSUE TITLE
it doesn't show the right lvl when submitting an exercise 

### ISSUE THREAD

**Issue by freeworldwhoo** [01-edu/public#1031]
when I submitted an exercise it gave me this 

![levl error](https://user-images.githubusercontent.com/39562040/159920071-71455987-a0d6-413f-84aa-2b35e7a79458.png)

but my lvl is 20  

![levl error actual lvl](https://user-images.githubusercontent.com/39562040/159920157-3ad94505-8796-45c1-bf86-8e5fd83fe093.png)
 
I think that the exams earned xp was not included in the calculation

**Comment by ZoeVig** [comment]
Hi @freeworldwhoo this might be because your level within a piscine is not the same as your level in the main curriculum and you are looking at different dashboards.

I'd need to have more info on this issue to look into it.
I'm closing this ticket as wonly use github public issues for content-related feedback. If this is still happening, please let your school admins know so that they can open a bug ticket (they know where!).

Many thanks!
Zoe
