### ISSUE TITLE
negative count down

### ISSUE THREAD

**Issue by freeworldwhoo** [01-edu/public#1034]
If you are in the page of the count down for a quest when it goes to 0 it doesn't stop it keeps going with negative numbers

![countdown negative](https://user-images.githubusercontent.com/39562040/160091051-9f3f1532-1659-4c9e-9bb8-1b0c49182cd3.png)

**Comment by OGordoo** [comment]
I checked this and it seems to be a problem with the attributes. If `inScope` is true and `scopeEnd` has already passed, the date gets negative values. @kigiri what do you think of this?

**Comment by ZoeVig** [comment]
Hi @freeworldwhoo!

Thank you for reporting this, we use github issues for content-related feedback only so this ended up falling through the cracks (our bad!)

I'll close this ticket, if this is still happening, could you please report this to your school admins so that they can open a bug ticket?

Thank you :)
