### ISSUE TITLE
IsTriangle

### ISSUE THREAD

**Issue by zainabdnaya** [01-edu/public#1130]
Write a function that accepts 3 integer values a, b, and c.
    The function should return true if a triangle can be built with the 3 given sides (a,b,c) otherwise, it returns false.

```go
func IsTriangle(a, b, c int) bool{
}

```

```go

package main

import "fmt"

func main() {
	fmt.Println(IsTriangle(4, 2, 3))
    fmt.Println(IsTriangle(4, 2, 10))
}

```
```go
$ go run .
$true
$false

```

**Comment by zainabdnaya** [comment]
.

**Comment by davhojt** [comment]
What do `a`, `b`, and `c` relate to?

**Comment by zainabdnaya** [comment]
a,b,c represents the length of each side which may build  a triangle or not , 
I guess my explanation of the exercise is weak.

**Comment by davhojt** [comment]
Okay, it seems reasonable.

Let's have a little go at describing how a triangle can be formed. Perhaps we can call it a "special triangle" or something like that. For example, the length of the shorter sides must be at least 30% longer than the longest side.

Otherwise, I guess people may get confused about very flat triangles 😅. Like:
a 9.999999...
b 5
c 5

No problem, that's a reasonable exercise. We may need to have a think about how triangles can be formed, and to think about expressing this in the topic.

**Comment by zainabdnaya** [comment]
to know if any  three side lengths can make a triangle you just use the  Triangle Inequality Theorem , Not matter what the shape of the Triangle

**Comment by davhojt** [comment]
The exercise is a good one, but it must include an explanation. The student will not have access to the internet to research theorems. We're assessing their ability to program at an elementary level (rather than their knowledge of theorems).

**Comment by zainabdnaya** [comment]
> The exercise is a good one, but it must include an explanation. The student will not have access to the internet to research theorems. We're assessing their ability to program at an elementary level (rather than their knowledge of theorems).

Actually, You are correct these are not days' exercises!
