### ISSUE TITLE
borrow_box subject

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#1416]
borrow_box
---
The instructions say:
![image](https://user-images.githubusercontent.com/80747520/188436203-a5bcfb95-ea1d-4ba1-82ad-14202cc0281d.png)

To pass the tests the `nbr_of_games` should neither be incremented or decremented. It should remain untouched.

**Comment by mikysett** [comment]
Correct code decrements `nbr_of_games` and passes all tests.
When leaving `nbr_of_games` untouched the following test fails:
```
tests::test_update_and_read' panicked at 'assertion failed: `(left == right)`
  left: `("Same score! tied", 1)`,
 right: `("player1", 1)`test tests::test_different_name ... ', oksrc/lib.rs
```
So at the moment tests seems to follow the subject (but subject should say `decremented` instead of `incremented`.
In case further investigation is requested I should have the code creating the issue, otherwise I won't be able to reproduce the error.

**Comment by jarmo-seljamaa** [comment]
My code did not touch `nbr_of_games` and passed all tests. I gave @mikysett access to a repo that contains that code.

**Comment by mikysett** [comment]
Thank you a lot for your contribution, it is now way clearer.
Effectively `nbr_of_games` should not be incremented or decremented.
Also your code helped us to find out one edge case was not tested (the expected behavior is not to change scores if one player has already won, like 3-0 out of 5 should never become 4-0 out of 5).
Changes are now in review and will shortly be applied in production.
