### ISSUE TITLE
highest subject

### ISSUE THREAD

**Issue by silverpedak** [01-edu/public#1454]
highest
---
In "here's a program to test your function" theres a struct being defined which should be in "expected function" instead. Can be misleading to some..

**Comment by eslopfer** [comment]
Hi @silverpedak thanks for your feedback.

Expected functions are the functions' signatures the learner has to write.
In order to test it locally, it has to be created, that's why it's being defined with the test.

Can you be a bit more specific about what part of it is misleading to see if there is something that we can clarify on the description of the exercise?

**Comment by silverpedak** [comment]
In every other exercise, the needed structs are defined in "expected function" part. But in "highest", the needed struct is defined in "Usage". To name a few examples of where they are defined in "expected function" - Project motion, step_iterator, iterators, sales. To test it locally, it doesn't have to be defined in main.rs. I have proposed a change, so maybe it's more clear what i mean.

**Comment by eslopfer** [comment]
Hi @silverpedak you were right.
This issue will be addressed on the linked pull request.
Thanks a lot again for your feedback.
