### ISSUE TITLE
iterators subject: Incomplete description and inaccurate usage

### ISSUE THREAD

**Issue by uristdwarf** [01-edu/public#1460]
iterators
---
The description doesn't describe what's the purpose of the iterator and the `Collatz` struct, which is required. It also doesn't describe when `None` should be returned
Furthermore, expected functions is incomplete (nowhere did it say that the struct needed a `new` method)
![image](https://user-images.githubusercontent.com/7394119/190869249-75f78f0f-f5c1-49e9-863c-d9c1b8a62a78.png)
Finally, usage is incorrect because we are supposed to use the struct, not `u64`

**Comment by uristdwarf** [comment]
Here's the description I wrote for other students
```
Create the function collatz as described in the description.
Implement new for Collatz which returns the struct, with v being the u64 given to it.
Implement Iterator trait for Collatz, with Item being type u64 and next() changing and returning the v.value to the next Collatz value. (Not steps, but the next value. For example .next(133) should change/return 400)
```

**Comment by jarmo-seljamaa** [comment]
I disagree, the instructions are clear enough with stating `Given a number n, return the number of steps required to reach 1.` + the usage example that clearly shows that an Option<value> is expected to return.

What is missing is the edge case of n = 0. Should we return `None` or `Some(0)`?

**Comment by mikysett** [comment]
Thanks a lot for the feedback, I've modified the subject and tests and here are some considerations:
- `new` is required, now this is explicit in the subject.
- Edge cases (0 and 1) are now given as an example.
- `collatz()` do not return an `Option` anymore since it can't fail, it will return instead a `usize`, so it works in a more idiomatic way.
- I've added more tests, they will ensure that `next()` return `None` when it is supposed to.
- To understand how an iterator works and how to implement it (what we are suppose to give as an output, do we modify the struct itself and so on) is the goal of the exercise, it is way better if students can look and find this information on their own, so I didn't gave any further details about how `next()` should be implemented (there is a standard way that Rust std library expect, this should be the guideline).
