### ISSUE TITLE
matrix_ops subject

### ISSUE THREAD

**Issue by azamatamirzhan** [01-edu/public#1598]
matrix_ops
---
in main.rs  first string need to be changed:

from:  use matrix::*;
to:       use matrix_ops::*;

**Comment by mikysett** [comment]
Thanks a lot for reporting this naming mismatch.
The fix is ready and will be pushed into production next week.
In the meanwhile you may have a mismatch also for the exercise `matrix_mult`.

If you want to try your solution before the fix is available you should rename `package` in the `Cargo.toml` of the project. The name should be `matrix`.
Of course this hack won't work after the fix will go into production. (then the packages should be `matrix_ops` and `matrix_mult` as usual and as automatically generated when running `cargo new --lib cargo_ops` or `cargo new --lib cargo_mult`)
