### ISSUE TITLE
gorilla packages no longer maintained/archived

### ISSUE THREAD

**Issue by uristdwarf** [01-edu/public#1656]
https://github.com/gorilla/.github/blob/master/profile/README.md

I recommend replacing some of the used gorilla websocket packages with those that at the very least will get security updates.

Some examples:
* [Go's own extended library version](https://pkg.go.dev/golang.org/x/net/websocket)
* [nhooyr/websocket](https://github.com/nhooyr/websocket)

**Comment by eslopfer** [comment]
Hi @uristdwarf thanks for the feedback. We are looking into the issue.

**Comment by eslopfer** [comment]
Hi @uristdwarf , since this package is still by far the most used websockets  implementation for Go, and it only recently has been archived, we decided to wait some time before deciding what to do regarding whether or not it would be sensible to replace it by another one.

If you look at releases this is a very stable implementation, it has been updated about once a year historically. It is even still recommended in the first link you suggested.

It is still too soon to know what is going to happen to it. They might find a maintainer, a company might step up and take charge of it, maybe someone will fork it and make a new version of it that gets widely adopted... no one knows yet.

We looked into it and will check again in the future what to do in this regard after some time has passed as stated before.

Nonetheless, thanks for raising the issue, don't feel discouraged to provide more feedback in the future,
