### ISSUE TITLE
make-your-game subject

### ISSUE THREAD

**Issue by danglam88** [01-edu/public#1798]
make-your-game
---
Hello again,

There is still one audit question that is quite unclear to us. The last audit question asks **"Is layer creation being promoted properly?"**. Is this question only asked when we choose to create layer? In other words, the complete question should be something like this: **"If layer has been created, is layer creation being promoted properly?"**. Is it correct? We understand that layer creation is NOT a must since the second last question asks **"Can you confirm that the layers are being used as little as possible?"** so it means NOT creating layer at all should be the BEST option. Do we understand it correctly?

Thanks very much for your consideration!

Best regards
Dang Lam

**Comment by MSilva95** [comment]
Hello @danglam88!
It is not specified that the use of layers is mandatory but we will change that accordingly.
Regarding the "as little as possible" part, we ask it this way because the use of layers can improve the rendering performance of a web page, but it's important to create them properly and minimize their usage to avoid performance issues.
Thank you for the catch!

**Comment by MSilva95** [comment]
we will add this line to the readme:
`- The use of layers must be minimum but not zero in order to optimize the rendering performance.`

**Comment by danglam88** [comment]
Thanks!
