### ISSUE TITLE
mobs subject

### ISSUE THREAD

**Issue by codecplyre** [01-edu/public#1809]
mobs
---
boss: which should contain:

    Boss: a struct which consists of:
        name: String
        age: u8
        new: an associated function which accepts a name and age, and returns a Boss.

member submodule which consists of:

    Role: an enum with the variants:
            Underboss
            Caporegime
            Soldier
            Associate
    Member: a struct which consists of:
        name: String
        role: Role
        age: u8 get_promotion: an associated function which when invoked should promote the member from:
                Associate -> Soldier
                Soldier -> Caporegime
                Caporegime -> Underboss
        new: accepts a name, role and age, returning a Member.
        
This part of the instructions above is confusing. The new function in the Boss struct is not part of the Boss struct in the given example instead it is part of the boss module

```rust
boss::new("Louie HaHa", 36);
```

the same as the new function in the Member struct 

```rust
member::new("Knuckles", member::Role::Soldier, 25)).
```
Let me know if this is intentional or not.

**Comment by mikysett** [comment]
Hello @codecplyre 

Once again thanks a lot for spotting this possible improvement.
Effectively it will be better to implement `new` as an associated function instead.
I've made the required changed on both `Boss` and `Member`.

When they will be pushed into production you will need to use `member::Member::new(..)` and `boss::Boss::new(..)` in order to call those functions, as we would expect from a usual crate ;)
