### ISSUE TITLE
lem-in objectives and audit controversy

### ISSUE THREAD

**Issue by Halkfr** [01-edu/public#1816]
Lem-in objectives says: 
- Some colonies will have many rooms and many links, but no path between ##start and ##end

**It is not clear what was intended:**
1. Non of example.txt will have ##start - ##end situation
2. Sometimes ##start will not be directly connected to ##end, but it is possible
3. Some graphs are going to be disconnected

For example, I understood this sentence as option 1. Due to that I could not pass example02.txt in lem-in audit as ##start has direct connection with ##end which ruins logic of my program.
```
$ go run . example02.txt
20
##start
0 2 0
1 4 1
2 6 0
##end
3 5 3
0-1
0-3
1-2
3-2

L1-3 L2-1
L2-2 L3-3 L4-1
L2-3 L4-2 L5-3 L6-1
L4-3 L6-2 L7-3 L8-1
L6-3 L8-2 L9-3 L10-1
L8-3 L10-2 L11-3 L12-1
L10-3 L12-2 L13-3 L14-1
L12-3 L14-2 L15-3 L16 -1
L14-3 L16-2 L17-3 L18-1
L16-3 L18-2 L19-3
L18-3 L20-3
$
```

If this is an intentional situation audit could have more examples where ##start is directly connected to ##end.

**Comment by mikysett** [comment]
Hello @Halkfr 
Thanks a lot for your report.

Concerning the subject:
- The sentence you quoted is pointing out that some inputs may result in disconnected graphs (which is of course an erroneous input since unsolvable).
- This sentence is in the section of the possible erroneous inputs (for example graphs without `##start` or `##end`), and must be treated as "Do checks because some inputs may be bad, and the program must still report errors nicely".

Concerning the `example02.txt`:
- I guess you quoted the answer in the audit instead of the output of your implementation (having your result would have been more enlightening tough :) )
- Well, I imagine your program makes all the ants pass from start to end in one turn since they are directly connected. If this is the behavior please consider this line of the subject:
```
- Each tunnel can only be used once per turn.
``` 

I'll close the issue for now but please feel free to reopen it and to write me back if you need more info
