### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by healingdrawing** [01-edu/public#1875]
**Describe the bug**
The graphql subject **do not have "Transactions" table in api**, but your description example uses this name for table.
The **transaction** table do not have access to audit ratio data, but your description says it has.
The graphql subject **do not have "Results" table in api**, but your description example uses this name for table.
The names in the description are capitalized , in same time in API the names are lowercase.

The allowed to use tables , with restricted number of columns (according to your description), are **do not have the "level" column**, which you say can be used.

You crap on reader at least 10 times , only inside description. It is not errors, it is level of quality, and level of responsibility.
Luckily AI will fix this soon. You have not more than 2 years. After that you will be kicked out from the market.

**Users**
Usernames of students/admin that are affected by the issue: anybody who can read i think

**Severity**
Choose the severity label (❗️minor), (‼️ major), or (⚠️ critical).

**Type**
Choose the label (🖌️ ui), (⚙️ functionality), (🗂️ documentation), or (🔐 security)

**To Reproduce**

just read your task , and check the api

**Workarounds**
Any known workarounds for the issue:

**Expected behavior**

**Attachments**
If applicable, add screenshots/videos/logs to help explain your problem.
<sub>Using tools like [Loom](https://chrome.google.com/webstore/detail/loom-for-chrome/liecbddmkiiihnedobmlmillhodjkdmb)</sub>

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davhojt** [comment]
You know: when you arrive in the workplace as a dev, you will certainly not receive beautifully detailed tasks in every instance. You'll need to ask questions about the problem you need to solve, and work with out-of date documentation. It's an acquired skill. Would you prefer to acquire it now, or later?

May I ask, since you started your journey through the curriculum, did your skills improve? I.e. have you learned anything by progressing through the curriculum?

> You crap on reader at least 10 times , only inside description. It is not errors, it is level of quality, and level of responsibility.
Luckily AI will fix this soon. You have not more than 2 years. After that you will be kicked out from the market.

I'm equally sure that if you communicate with your colleagues in this way, you will too be irradiated by AI. Nobody likes working with aggressive people.

Your feedback is appreciated and welcomed, but your aggression really isn't. I'm very sure that inaccuracies frustrate you, which comes across in your communication. I'm sure that when you're not frustrated, that you're wonderful to get along with. Please remember that your messages are reviewed by people (not AI). So try to communicate respectfully.
