### ISSUE TITLE
Rust Piscine

### ISSUE THREAD

**Issue by nik-don** [01-edu/public#1889]
### Quest 2
- **borrow**
Task can be completed using the built in methods using 1 liner.

### Quest 3
- **strings** 
Task can be completed using the built in methods using 1 liner.

- **collect** 
Task can be completed using the built in sort method.

### Exam
- **insertion_sort** 
can be completed using built in sort method.

I understand that these tasks may have been designed intentionally in this way, but I wanted to share my observations.

I would also like to add that I believe it would be helpful if we could receive clarification on whether the expected approach for writing Rust code is functional or imperative.

**Comment by mikysett** [comment]
Hello Nik, thanks a lot for your feedback.

It is ok to have one liners for some of those exercises (like `borrow`), while for others the expected outcome is to rewrite the function without using the standard implementation.

At the moment we don't have a system that automatically enforces this behavior for the Rust piscine, still I'm exploring possibilities for future improvements.

Concerning the better approach to write in Rust, the language is general enough to support both functional and imperative in a nice way.

Generally speaking the functional approach is considered more idiomatic, still we do not give specific information about it as we believe that style and best practices by experience than if imposed from the top.

As a suggestion and personal advice it would be nice to get used to `cargo clippy` and `cargo fmt` in order to improve the style the most common mistakes.

**Comment by mikysett** [comment]
Hello Nik,

I must thank you, this feedback is very valuable and really helps :)

As for the exercise you mentioned:
- [count_factorial_steps](https://github.com/01-edu/public/tree/master/subjects/count_factorial_steps): nice catch, fixed
- [scytale_decoder](https://github.com/01-edu/public/tree/master/subjects/scytale_decoder): I'm not sure to understand properly so correct me if I didn't. The tests are correct, but the error given is a bit cryptic and it's hard to take action from that right?
- [matrix_display](https://github.com/01-edu/public/tree/master/subjects/matrix_display): I do agree it's hard to guess signatures for such functions, I myself never remember them properly and always look into the std lib for it. Still I think it's better to create the habit to look for proper traits implementations on official documentation than give it in the subject though. (Since this is a habit to be taken anyway). Don't hesitate to propose a different approach ;) 

About the AI driven learning this is something we are discussing a lot internally lately, I'm very curious in case you have more details to share about it, how you felt it was useful and how you felt it was not helping to learn, also if you have so ideas on taking the best out of it in terms of learning procedures.

Have a really nice one and hope to hear from you soon

**Comment by nik-don** [comment]
> 
> [scytale_decoder](https://github.com/01-edu/public/tree/master/subjects/scytale_decoder): 
I'm not sure to understand properly so correct me if I didn't. The tests are correct, but the error given is a bit cryptic and it's hard to take action from that right?
> 

During the exam, while I was working on the solution and submitting it, the third test failed. I couldn't understand why my solution was missing a letter. Since I was pressed for time, **I was unsure whether the test input was incorrect** or **if my solution needed to be adjusted**. Because I could clearly see the expected result, I decided to hardcode the solution for the remaining tests. This issue could potentially encourage others to hardcode the solution as well. Maybe a random string generator could be implemented.

Regarding the use of AI assistance, I have some observations. I thoroughly enjoyed the Go Piscine, where we did not have access to it. In this environment, I found that there was a strong sense of collaboration among the students. However, I felt that this dynamic was less common in my Rust Piscine. I observed a range of approaches to using AI: some students effectively used it to solve problems by finding definitions or getting tips, while others seemed to adopt the AI-generated solutions without fully understanding them. Students didn't discuss the problem first and come to a solution; rather, they obtained a solution and discussed it afterward. This suggests the need for a more balanced use of AI assistance to ensure it supports learning rather than bypassing the problem-solving process.

I hope these insights contribute to improving the platform.
Alla prossima! 😁

**Comment by mikysett** [comment]
Thanks for clarifying about `scytale_decoder`, now I understand what you meant.
I think your suggestion is very valid, indeed we are thinking about randomizing inputs since a while.
I've noted the incriminated exercise. I won't hide this will fall into the bigger effort of improving general exercise structure it will probably take a while.

About the AI, your feedback will help us guiding the discussion on how to make the best out of it or which kind of cases we won't to prevent from happening.

Once again thanks a lot and have a very good time learning (especially Rust, which is my favorite :D)
