### ISSUE TITLE
unbreakable subject [tester see [object Array] where I see string]

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#1960]
unbreakable
---
everything works perfectly on my machine but,
output of the tester :
```
test #9 failed:
() => join(['ee', 'ff', 'g', ''], ',') === 'ee,ff,g,'
```
when I slip a console.log into the code I can see that the tester compute that instead of proper string :
`[object Array],[object Array],[object Array],[object Array]`

sounds like of of those function ban , break my code. but I would expect something to pop up to tell me.
String.prototype.split = undefined
String.prototype.match = undefined
RegExp.prototype.exec = undefined
Array.prototype.join = undefined

I have linux with node version 19.8.1

**Comment by fulverin** [comment]
this is 
Array.prototype.join = undefined

**Comment by fulverin** [comment]
I ran all individual function I use in my code with Array.prototype.join  = undefined and it worked

**Comment by fulverin** [comment]
I observed that node's REPL do not parse correctly code I paste inside, after the Array.prototype.join have been undefined.
I suspect some reflection at play; where the tester rely on those function to test the code and cannot parse it because it not defined anymore.

**Comment by nprimo** [comment]
Please, have a better check at the [subject's last section](https://github.com/01-edu/public/blob/master/subjects/unbreakable/README.md) ;)

**Comment by fulverin** [comment]
sorry if it wasn't clear , well it was not for me.
but the issue is not that some function are "deactivated" , and I wasn't using it.
the issue is that doing 
`Array.prototype.join = undefined`
modify the result of :
`['text']+['other']' 
and do not throw any error :
try it in REPL:
`['text']+['other']' 
// give    ->   'textother'
`Array.prototype.join = undefined`
`['text']+['other']' 
// give - > [object Array],[object Array]
// and it is not even clear if it a string or an Object

Issue is probably upstream and you may argue it is about learning the hard way.
but if there is a learning here I am not sure it worth the 2 hours it takes to figure out.
Mentioning the issue in instruction or the tester would spare headache to students,
unless deactivating builtin function is real world situation.
maybe something like :
'note that the + operator may rely on join method and should be avoided too'

**Comment by nprimo** [comment]
I understand the confusion. The "issue" here is that, under the hood, JavaScript is doing things that are not always as transparent as you would. In this specific case (`['a'] + ['b']`), probably an `Array.prototype.join` is used and therefore, when you set that as `undefined` you get your "weird" result :) 

I feel the subject is clear enough because you can easily test your code with the line `Array.prototype.join = undefined` in your code (it is quite clear that the solution will be tested in a script that will have this line included). Adding this specific case would not "be exhaustive" since I don't personally know if there are other cases like the one you described. 

I hope this clarifies the issue for you. Have a great weekend and all the best for your piscine :muscle:

**Comment by fulverin** [comment]
thank you,
So if you forgive my stubbornness, I would like to suggest an idea I have just tested.
Instead of  `Array.prototype.join = undefined` you do `Array.prototype.join = ()=>(console.log('not allowed'))`
then things get really explicit and the lack of error message from JS is solved.
