### ISSUE TITLE
printalphabet subject

### ISSUE THREAD

**Issue by al3skry10** [01-edu/public#2020]
printalphabet
---
I have an issue on eun my test on the website, https://learn.reboot01.com/.
However I can find the file in the prober forder nside the websit, and the coding give my the same result that required. 
but im stiil gitting this massege : '' Error: Get file info failed: Not Found''

Waiting for your feedback, thanks

**Comment by mikysett** [comment]
Hello @al3skry10 

It seems like you are not uploading the file (or not correctly) into your Gitea repository.

From the exercise I suppose you are just starting the Go piscine so it may be you are just starting your journey into programming.

I guess you already found what was causing the error by now, if not try to look into the firsts introduction videos which explain a bit how to use `git` in order to upload your solutions.

It will be also very good to ask around to others that may have already solved the issue ;)

In case you still can't manage to upload your solution and you think it's due to some issues with the platform please don't hesitate to reopen this issue.

Wish you good luck and a lot of fun ;)
