### ISSUE TITLE
mini-framework subject audit

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2026]
mini-framework
---

1. The following audit question seems to be unnecessary:

> [Does the documentation contains an explanation of every feature of the framework?](https://github.com/01-edu/public/tree/master/subjects/mini-framework/audit#does-the-documentation-contains-an-explanation-of-every-feature-of-the-framework)

The same question is covered in more detail in the next question:

> [Does the documentation contains an explanation and code examples on how to create an element, add attributes to an element, create an event and nest elements?](https://github.com/01-edu/public/tree/master/subjects/mini-framework/audit#does-the-documentation-contains-an-explanation-and-code-examples-on-how-to-create-an-element-add-attributes-to-an-element-create-an-event-and-nest-elements)

As an auditor it is hard for me to answer to the first question, as it is difficult to tell if *EVERY* feature of the framework has been documented. It is quite easy to answer to the second question, which gives a definite list of features that need to be explained in the documentation.

2. The bonus part asks again about the usage of "synchronicity". Is it possibly the same issue as reported here?
[ #1008 ](https://github.com/01-edu/public/issues/1008)

**Comment by mikysett** [comment]
Hello @jarmo-seljamaa 

As usual thanks for your commitment to help us improve the content ;)

I've made the first question more focused on having a top-level overview of the features so the scope will be clearer.

I've fixed also to typo about "synchronicity" and few other I found on the way.

Have a nice one ;)

**Comment by jarmo-seljamaa** [comment]
Thanks for the response! I feel that now the first question about `top-level overview of the framework's features` is rather similar to the third question about `an explanation on how the framework works`, don't you think?

**Comment by mikysett** [comment]
Yes the questions seems indeed quite similar, still one puts the main focus on what the framework do and the other one on how it do it.
While those two info are quite similar and in small projects they are often mixed, it is useful and important to think about them separately for better management.

As an example:
We can say Google.com and ChatGPT both help you find the answers to your questions providing useful info, in that sense the features they offer is the same.
How they work in order to achieve that goal is though very different :)
