### ISSUE TITLE
social-network subject

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#2134]
social-network
---
Hello,
I think that the wording about users interactions is really confusing.

> In order to follow someone the user first needs to send a request to the user he/she wants to follow. Then the other user should be able to accept the request or decline it. If the second user has a public profile (explained in the next topic) this step is skipped and the sending of the request is ignored.

if Bob accept to follow Marie then Marie become Bob's follower too ?
in short , is it reciprocal ?
Instructions are ambiguous about that and I hardly see Bob being able to start chatting with Marie and not the other way around.

the sending of the request is ignored ? or the request is ignored , or the acceptance/refusal step of the request is ignored
if Bob is public, can Marie follow Bob without need of acceptance ?

if someone can rephrase that sentence:
> The user that the message was sent to, will receive the message instantly, by the usage of Websockets, if he/she is following the user that sent the message or if the user has a public profile.

sorry , I never used tweeter or Instagram...

**Comment by MSilva95** [comment]
Hello @fulverin!

Regarding following someone, the user must initiate this by sending a "follow request" to the desired user. The recipient user can then choose to accept or decline the request. However, if the recipient user has a public profile (as explained in the next section), this request-and-accept process is bypassed.

regarding the "if Bob is public, can Marie follow Bob without need of acceptance ?" the answer is yes, since Bob is public.

regarding the,  "is it reciprocal ?"
No it is not! But it only needs one of them to follow the other to initiate a chat! So if both profiles are private and only Marie follows bob, they can still initiate a chat.

I will make this clearer in the subject, thank you for the feedback!

**Comment by fulverin** [comment]
> So if both profiles are private and only Marie follows bob, they can still initiate a chat.
thanks a lot.

**Comment by MSilva95** [comment]
No, sorry i messed up in the comment i just edited

regarding the, "is it reciprocal ?"
No it is not! If both profiles are private and only Marie follows bob, they can not initiate a chat. Only if both of them are following each other

**Comment by MSilva95** [comment]
Yes, that is it! i was going to change it but it doesn't make sense...
If one of them  accepts the follow request, they will be accepting the possibility of messages as well
