### ISSUE TITLE
Mini framework question 

### ISSUE THREAD

**Issue by mathisen99** [01-edu/public#2136]
Just got a quick question is react allowed to be used for this project?

**Comment by bomanviktor** [comment]
From the front page of react: [The library for web and native user interfaces](https://react.dev/)


From the project description of [mini-framework](https://github.com/01-edu/public/tree/master/subjects/mini-framework):
```
Be aware that a framework is different from a library. When you call a method from a library, you are in control. But with a framework, the control is inverted: the framework calls you.
```

However, it is not specified anywhere in the project description or the audit questions that libraries can't be used for this project. Since it has been specified that you are not allowed libraries or frameworks in earlier projects (looking at you, [forum](https://github.com/01-edu/public/tree/master/subjects/forum)), and it's not specified anywhere here, rather encouraged, I would say that it is allowed. 

If it is not intended to be allowed, I suggest the project description should change along with the audit questions and following line be added to the project description:
> You must not use use any frontend libraries or frameworks like React, Angular, Vue etc.
