### ISSUE TITLE
Update rand in card_deck in Rust Piscine

### ISSUE THREAD

**Issue by sagarishere** [01-edu/public#2144]
0.3.14 was released 7 years ago and breaking changes have occurred in newer versions.

Kindly update here and in the backend in tests.

**Comment by nprimo** [comment]
Due to the current way our test suite is working, doing so will cause some issues. I will add a link to the documentation of this old crate version to avoid investing extra time in looking for that documentation.

Being forced to use outdated packages/libraries/crates, unfortunately, is quite recurrent in software development :)
