### ISSUE TITLE
printstr subject

### ISSUE THREAD

**Issue by sloth4roues** [01-edu/public#2179]
printstr
---
There is a huge problem with my printstr subject.
I literally put the EXACTLY SAME code that another person.
He got the "Bim"
I got the "Oh Snap!"

Here is my code :

```go
package piscine

import "github.com/01-edu/z01"

func PrintStr(s string) {
	aStringChangeable := []byte(s)
	x := 0
	for x != len(aStringChangeable) {
		z01.PrintRune(rune(aStringChangeable[x]))
		x++
	}
}

```

**Comment by sloth4roues** [comment]
nathan.walter@ynov.com
I can respond here quickly.

**Comment by mikysett** [comment]
hello @sloth4roues 

I'm looking into it and try to come back to you as quick as possible.

In the meanwhile can I ask you if you can send us the error message you got (if any), or if you already solved the issue maybe?

Thanks a lot for the feedback and help in solving this issue ;)

**Comment by sloth4roues** [comment]
Hi mikysett, thanks for the response !
I passed it, but I submit another code ( still not normal that the previous one doesn't go well ).
But I have another issue ! 

with this code on the first task, quest-4 :

```go
package piscine

func IterativeFactorial(nb int) int {
	x := 1
	result := 1
	if nb < 0 || nb > 20 {
		result = 0
		return result
	}
	if nb == 0 {
		result = 1
		return result
	}
	for x <= nb {
		result = x * result
		x++
	}
	return result
}
```

I got this error :

```
Your Go files are not correctly formatted :

$ gofumpt -d .
diff -u iterativefactorial.go.orig iterativefactorial.go
--- iterativefactorial.go.orig
+++ iterativefactorial.go
@@ -1,19 +1,19 @@
-package piscine
-
-func IterativeFactorial(nb int) int {
-	x := 1
-	result := 1
-	if nb < 0 || nb > 20 {
-		result = 0
-		return result
-	}
-	if nb == 0 {
-		result = 1
-		return result
-	}
-	for x <= nb {
-		result = x * result
-		x++
-	}
-	return result
-}
+package piscine
+
+func IterativeFactorial(nb int) int {
+	x := 1
+	result := 1
+	if nb < 0 || nb > 20 {
+		result = 0
+		return result
+	}
+	if nb == 0 {
+		result = 1
+		return result
+	}
+	for x <= nb {
+		result = x * result
+		x++
+	}
+	return result
+}
```

Thank you so much for taking the time to answer.
"Your Go files are not correctly formatted :"
But the "---" and the "+++" are literally the same !

I got too often this error so if you can help me, it would mean the world !

**Comment by mikysett** [comment]
Hello @sloth4roues 

Thanks for reporting this new issue.

It is very hard for me to be assertive about this kind of problems since I can't reproduce it with the provided info (and in this specific case it seems very hard to provide the right input for the task).

If this will happens again I would suggest to do couple of things:
- Run `gofumpt -d .` locally and see if it gives the same error.
- Check if you use tab or spaces for indentation, maybe you are not using the convention enforced by `gofumpt`.
- Check if you have any trailing spaces (after the text), this is a very common mistake and it's hard to catch.
- If none of those gave good results try to check your file encoding, maybe the files that gives the error are `utf-16` and the ones passing `utf-8`

Maybe the error is given only when you create a file on Windows/Linux or on a specific text editor (for example using the wrong new-line character for the specified system).

Those issues are quite common in some spaces and unfortunately they require a lot of patience and trial/error to be solved.

If you find any more info please write back on this issue and I'll reopen it and try to help further.

Have a nice one,
Michele

**Comment by sloth4roues** [comment]
Hello, I have just discovered and understood my error.
It's at the line breaks level, I'm sending a screen for more explanations :
![image](https://github.com/01-edu/public/assets/144029283/657d64e6-3d16-4023-b360-7e7293522eca)
It MUST be on LF and not on CRLF. It's an error that a human can't see but Ytrack see this.
Thanks to my teacher and thanks to you for trying to help me.
Beside Ytrack, have a good life man !
