### ISSUE TITLE
mini-framwork subject {wording}

### ISSUE THREAD

**Issue by fulverin** [01-edu/public#2182]
social-network
---
In this paragraph :
> State Management
> 
> The state of an app can be seen as the outcome of all of the actions that the user has taken since the page loaded. In other words, if a user clicks on a button to execute an action, the state should then change.
> What you will need to do is to implement a way to handle this state. Remember that multiple pages can need to interact with the same state, so you need to find a way to let the state be reachable at every time.  

that phrase :

> Remember that multiple pages can need to interact with ...  

I would say " Remember that multiple pages _**may**_ need to interact with ..."
I am not a native English speaker so I can not guarantee the value of my suggestion.

Here is my attempt to reformulate the block:

> The app's current state is the result of the previous state and any interaction since last state. The initial state being the first page after loading.
> A user modifying anything on the page by clicking on a button, performs an update from the previous state to the next one.
> You will implement the logic that updates the state. Remember that the same state may be shared by different pages, so it should be accessible across pages.

**Comment by mikysett** [comment]
Hello @fulverin and thanks a lot for this contribution also,

You are right and there is a typo in the subject which is fixed by this PR

I also like the rephrase of the "State Management" definition, still I won't implement it because here the goal is not to give the best in class definition about what state management is but just to give the bare minimum info so resources can be found about the subject if someone wants to deep-dive.
