### ISSUE TITLE
filler subject

### ISSUE THREAD

**Issue by sailordi** [01-edu/public#2226]
filler
---
Not enugh information is given about the task.

Does the game engine handle the robots (the ones given and the one we make)
Is the robot given the field and pice by the game engine.
Is it the game engine that gives us where the robot wants to place the piece
Do we or the game engine place the piece.

The task text is not wery clear. It needs to give more info on what is needed and what the components given does. 
Some sudo code would be helpful.

**Comment by mikysett** [comment]
Hello @sailordi 

Thanks a lot for the feedback about filler.

The subject may seem minimal but if you give it a deeper look you'll see all the questions you are asking are answered in it.

Let's see the questions in order:

> Does the game engine handle the robots (the ones given and the one we make)

>  Is the robot given the field and piece by the game engine.

As per the subject "- The `game_engine` will run your program and write the Anfield and the piece to place in the standard input."

So the game engine runs the players and writes in their standard input the map in the current state and the piece they'll have to place.

> Is it the game engine that gives us where the robot wants to place the piece

> Do we or the game engine place the piece.

Here also we got "- In order to place the game piece on the Anfield, the player will have to write it’s coordinates on the standard output. - The following format must be used `X Y\n`."

So it is the robot responsibility to write in the standard output where they want to place the piece they were given.

## To recap:

The sole role of a robot is to read the map, read the piece to place, and write the coordinates were to place the piece.
The beauty of the game is to create a robot able to place his pieces in a way that will occupy as much space in the map as it can in order to win the game.

Some little tricks to be aware of:
- The first time the game engine will write something to the robot it will also include info about the player number of the robot (this is fundamental for placing on `a/@` or `s/$`).
- Recently the `game_engine` and `robots` have been renamed to `linux_game_engine | m1_game_engine` and `linux_robots | m1_robots` to be executed also on M1 Macs, you'll need to change the commands names accordingly when testing your players.

I hope this will help and I'll close the issue for now.
If you have any further doubts feel free to write them down here and I'll be glad to reopen it ;)
