### ISSUE TITLE
listpushback subject

### ISSUE THREAD

**Issue by marekw34** [01-edu/public#2237]
listpushback
---
Error: Get repository info failed: Not Found

**Comment by mikysett** [comment]
Hello @marekw34 

Thanks a lot for writing to us, in order to help I'll need couple more info about the issue.

- Are you the only one facing the issue or there is other learners concerned?
- Did you already faced this issue in past? If yes did you manage to solve it and how?

This kind of error usually occurs when the Git repo used for your solutions doesn't exist or have the wrong name or the wrong authorizations.
It may also be that there is a misspell in the name of the files to be provided (so the platform can't find the files to test).

It would be very nice if you can compare your repo structure with one of your peers which already passed the exercise.

**Comment by mikysett** [comment]
I'll close the issue since there is not enough info to take action.

Feel free to write back here and I'll be glad to reopen it :)
