### ISSUE TITLE
Localhost audit questions

### ISSUE THREAD

**Issue by mathisen99** [01-edu/public#2322]
1. Setup multiple servers with different hostnames (for example: curl --resolve test.com:80:127.0.0.1 http://test.com/).
Should 2 diffrent servers listen/respond to same ip and port ??

2. Configure the same port multiple times. The server should find the error.
is this ment for same server or for diffrent servers ??

3. Configure multiple servers at the same time with different configurations but with common ports. Ask why the server should work if one of the configurations isn't working.
does this mean it should fail because common port ? or just a syntax error in the config file ? or should it just not start with multiple entries in the config for the Hostname/ip/port ? 

some clearification on these questions would be nice thanks!

**Comment by MSilva95** [comment]
Hello @mathisen99 i will take a look into the project and get back to you, thank you for the feedback

**Comment by MSilva95** [comment]
I will try to update the audit to be more understandable, but here is some reply that might help you right away:

- "Setup multiple servers with different hostnames (for example: curl --resolve test.com:80:127.0.0.1 http://test.com/).
Should 2 diffrent servers listen/respond to same ip and port ??"

The question in the audit aims to confirm if your server correctly distinguishes between requests for different hostnames even though they resolve to the same IP and port.

- "Configure the same port multiple times. The server should find the error.
is this ment for same server or for diffrent servers ??"

This question in the audit aims to check how your server handles configuration errors or conflicts. If you configure the same port multiple times within your server's configuration file for the same or different servers, the expectation is that your server should catch this error and handle it appropriately.  It's about ensuring that your server can identify the misconfigurations.

- "Configure multiple servers at the same time with different configurations but with common ports. Ask why the server should work if one of the configurations isn't working.
does this mean it should fail because common port ? or just a syntax error in the config file ? or should it just not start with multiple entries in the config for the Hostname/ip/port ? "

This question aims to validate your server's configuration handling.
You'll configure multiple servers simultaneously, each with different configurations but with shared ports. If one of these configurations isn't valid or encounters an issue, your server should continue to function for the other configurations without being entirely disrupted. The purpose is to ensure that an error in one server's configuration doesn't bring down the entire server if other configurations are correctly set up.
