### ISSUE TITLE
[FEATURE] ai-branch environments setup

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2348]
ai
---
Considering that [the whole branch will be reviewed](https://github.com/01-edu/public/issues/2330#issuecomment-1842743622) you might want to reconsider the 00 tasks of each day. These consist of setting up a new environment for each quest. Most of the quests actually use pretty much the same libraries, so building a new environment each day simply creates digital waste. I gave up building new environments pretty soon because I could easily use my already existing environment.

It would make sense to practice creating environments perhaps at the beginning of each week. But I think as we progress through the quests it would be worth to learn also how to update the environment with the required libraries as we go. Not to mention that the environment lists were incomplete (you updated the ones I reported, but there are actually two places in each quest where the environment setup is described and you often missed one of them).

**Comment by jarmo-seljamaa** [comment]
Another general remark is that all expected value results in the audits should be manually re-checked. About 1/4 of the times it was not possible to get the same result as audit presented. However comparing our solutions with other people in the piscine we concluded that there was nothing wrong in our solutions. So we simply ignored the mismatch in the results, as long as they were generally in the same range or looked plausible.

**Comment by Oumaimafisaoui** [comment]
Hello @jarmo-seljamaa , we understand your perspective on the repetitive nature of setting up virtual environments for each quest. However, we'd like to explain why this approach is actually beneficial:

Consistency and Isolation: Creating a new environment for each quest ensures a clean, isolated workspace. This prevents conflicts between different library versions and allows each quest to have its exact required dependencies.
Real-world Practice: In professional settings, it's common to create separate environments for different projects or tasks. This habit helps maintain clean, reproducible development environments.
Troubleshooting: If issues arise, having isolated environments makes it easier to identify and resolve problems without affecting other work.
Skill Reinforcement: Regularly setting up environments reinforces this crucial skill, making it second nature for future projects.
Version Control: It allows you to specify exact versions of libraries for each quest, ensuring consistency across different systems and over time.
Cleanup and Resource Management: Creating and deleting environments as needed is a good practice for managing system resources and keeping your development setup clean.

While it might seem redundant, the repetition is intentional to build good habits and reinforce best practices in Python development. As you progress in your career, you'll likely appreciate the benefits of this approach.

https://new.pythonforengineers.com/blog/python-tip-always-use-a-virtual-environment/
https://csguide.cs.princeton.edu/software/virtualenv#:~:text=Always%20use%20a%20Virtual%20Environment,-Always.&text=Virtual%20environments%20let%20you%20have,many%20venvs%20as%20you%20want.
