### ISSUE TITLE
throttle subject

### ISSUE THREAD

**Issue by vechivar** [01-edu/public#2358]
Hello,

As i was working on reproducing the leading and trailing options of the lodash throttle function, I tried several test with the original lodash function and found some behaviors I just can't understand.

My testing code :

import _ from 'lodash'

const start = Date.now()

const test = (x) => {
    console.log(x)
    console.log(Date.now() - start)
 }

const log = _.throttle(test, 1000, {leading: true, trailing:true})

log('A')
setTimeout(log, 700, 'B')
setTimeout(log, 1200, 'C')
setTimeout(log, 2300, 'D')

The result output :

A
0
B
1008
C
2211
D
2301

I would really like to get some explanation because this behavior just breaks everything I thought I understood...

Thank you !

**Comment by zanninso** [comment]
Hello @vechivar I extend your test to make me understand well the this weird behavior and I make it look like the following:
log('A')
setTimeout(log, 700, 'B')
setTimeout(log, 1201, 'C')
setTimeout(log, 2400, 'D')
setTimeout(log, 2500, 'E')
setTimeout(log, 3500, 'F')
setTimeout(log, 4000, 'G')
and the output is :
A
3
B
1001
C
2206
D
2404
E
3406
F
3505
G
4506

So here you can see that the unusual behavior is recurring, allowing us to explain it.
Initially, this happened only when you used leading and trailing simultaneously; therefore, in this case, this is how the throttled method works:

First Call ('A') at ~3ms: Executes immediately due to leading: true. It initiates the throttle period.

Second Call ('B') at ~1001ms: Occurs within the throttle period of the first call. It's delayed and executed at the trailing edge of this period, which is around 1000ms after the first call.

Third Call ('C') at ~2206ms: This call is made shortly after the second call's throttle period ends (1201ms after the start). However, since it's within the new throttle period initiated by 'B', it's delayed. It doesn't execute at 2000ms (which would be 1000ms after 'B') because the call at 1201ms resets the throttle timer. Therefore, it executes approximately 1000ms after 1201ms, which aligns with your observed time of 2206ms.

Fourth Call ('D') at ~2404ms: Made at 2400ms, it's outside the throttle period of 'C' and thus executes almost immediately due to leading: true.

Fifth Call ('E') at ~3406ms: Occurs within the throttle period of 'D'. The throttle timer is reset at the time of 'D's execution (2404ms), causing 'E' to execute approximately 1000ms later, at 3406ms.

Sixth Call ('F') at ~3505ms: Since it's outside the throttle period of 'E', it executes immediately due to leading: true.

Seventh Call ('G') at ~4506ms: Happens within the throttle period of 'F', and thus is executed at the trailing edge, approximately 1000ms after 'F'.

conclusion:
after the first two calls, the function alternates between executing calls immediately (due to leading: true) and delaying calls to the end of the new throttle period (due to trailing: true and the timer reset with each call). This pattern results in a "staggered" execution of calls, with every other call being delayed.

**Comment by vechivar** [comment]
Thank you for taking the time to answer my question.

I've seen an other behavior that don't make sense to me. This :

log('A')
setTimeout(log, 700, 'B')
setTimeout(log, 1200, 'C')

Outputs :

A
0
B
1025
C
2202

Just as before. But adding D like this :

log('A')
setTimeout(log, 700, 'B')
setTimeout(log, 1200, 'C')
setTimeout(log, 2100, 'D')

Outptus : 

A
1
B
1000
D
2126

Where the D event append before the C event of the previous test. It looks like D is allowed to execute instantly because the B throttle period is over, as doing setTimeout(log, 1900, 'D') instead results in D ~2200 . So to replicate this behavior you have to keep track of several throttle period that interact with each other in a very weird way.

I don't understand why this whole implementation is made so complicated, and why using the leading and trailing option simultaneously results in a behavior that is conflicting with the basic principle of throttle ("Creates a throttled function that only invokes func at most once per every wait milliseconds. " according to lodash documentation), instead of just doing something intuitive

**Comment by zanninso** [comment]
because the last call come in the edge time so it run directly because of the leading and in case you set the last call to be at 1900 then this call will be out of the edge time and that why it wait until the end of the wait time.

you can investigate about the edge time and do more test to know how much is the edge time.
