### ISSUE TITLE
point subject

### ISSUE THREAD

**Issue by oriax11** [01-edu/public#2393]
point
---
Hey i had problems with this task i didnt quite understand how can i print with only 4 printrune limit 
but a fellow condidate succeded at this task with this code 
```package main

import "github.com/01-edu/z01"

var str string = "x = 42, y = 21\n"

func main() {
	for _, char := range str {
		z01.PrintRune(char)
	}
}
```
this do not meet any requirement btw
i think there is a problem with the testing 
at first i tried this 
```
package main

import "fmt"
type point struct {
	x int 
	y int 
}
func setPoint(ptr *point, n, m int) {
	ptr.x = n
	ptr.y = m
}

func main() {
	points :=&point{}

	setPoint(points, 42, 21)

	fmt.Printf("x = %d, y = %d\n", points.x, points.y)
}
``` 
but was wrong xd
unvalid import fmt

**Comment by nprimo** [comment]
@oriax11 the exercise only allows you to use `z01.PrintRune` 4 times, so you get the error for importing `fmt`. The tests could always be improved but your implementation is wrong in this case :) 

@TomPadmanathan, please, do not share your solution with people who still have to resolve an exercise: this is not helpful since it's not going to make them learn as much as solving the problem themselves :)
