### ISSUE TITLE
Cat quest 08 Levell 22: Error: Get file info failed: Not Found

### ISSUE THREAD

**Issue by TomPadmanathan** [01-edu/public#2398]
The question "cat" on quest 08 is returning this error: "Error: Get file info failed: Not Found". Another person has been experiencing the same issue. All the necessary files have been pushed to git in multiple locations, however nothing has gotten rid of this error.

**Comment by Amiano-Abreu** [comment]
I also am receiving the same error. Hope it's resolved soon.

**Comment by MSilva95** [comment]
Hello @TomPadmanathan!
This exercise was updated to only have as expected file the "main.go". This means that you have a version of the exercise that is not updated. To resolve this, you will have to contact the responsible administrator at the school where you are so that they can update the exercise duplicated reference.

**Comment by MSilva95** [comment]
Is this still a problem! @TomPadmanathan?

**Comment by TomPadmanathan** [comment]
Thanks for the reply. I contacted the school admin and they updated the exercise.
