### ISSUE TITLE
printalphabet

### ISSUE THREAD

**Issue by chaliazo** [01-edu/public#2402]
I ran printalphabet and was successful,on going to next step which is printreversealphabet ,i tried to run it the it took me back to printalphabet which has refused to go through,
---

**Comment by Stevovenom** [comment]
I had experienced the same issue

**Comment by MSilva95** [comment]
Hello @Stevovenom  and @chaliazo!
Can you tell me if you were using the code editor when you did the  'printalphabet' and then stopped using the code editor?

**Comment by chaliazo** [comment]
I  was using code editor and now the time has run out,so I don't need your
help,and I've given up on that thing, how can I manage something then your
system decides to misbehave then I consulted earlier no response until the
time has run out

**Comment by MSilva95** [comment]
Hello @chaliazo!
We understand the frustration, but as you may know, bugs happen when we create new features.
Regarding the time that we took to reply, we replied in the same day, the description of the issue is not good, there is no details about the issue, so we did the best with what we had. 
The problem here will probably be that you didn't format your code well in the first "printalphabet" exercise and if it isn't formatted well when you try to submit the next exercise you will get an error.

**Comment by chaliazo** [comment]
So what should I do since the time had already passed,now I can't continue

**Comment by MSilva95** [comment]
Hello @chaliazo and  @Stevovenom!
There is a chance that you might receive XP assigned by a school admin. You would need to contact him and explain your situation.
The admin will probably ask you to complete the tasks before awarding you the XP
This is the process that will give you a positive outcome

**Comment by chaliazo** [comment]
How do I contact the school admin and for now I've not been to that school
for two days now am behind I can't compete so far

**Comment by MSilva95** [comment]
I Will tag the support team so that they try to help you with that!
@freeworldwhoo

**Comment by chaliazo** [comment]
Those support teams are very rude,I approached them earlier but they just
talked to me ruthlessly,for sure it's not fair

**Comment by freeworldwhoo** [comment]
the issue is fixed
