### ISSUE TITLE
[QUESTION] emotions-detector subject requirements reasonable?

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2451]
emotions-detector
---
The Step 1 instructions in the [Face Emotions Classication](https://github.com/01-edu/public/tree/master/subjects/ai/emotions-detector#face-emotions-classification) says:

>  The CNN has to perform more than 70% on the test set.

However looking at very many different CNN implementations at [Kaggle forums](https://www.kaggle.com/search?q=fer+2013) on the FER 2013 dataset, I have not yet found a single one that achieves more than 66% accuracy on the test set. I have tried more than 50 different configurations of CNN layers and it's starting to feel like a waste of time.

The provided [link to a VGG architecture example](https://www.quora.com/What-is-the-VGG-neural-network) is not particularly helpful, as takes input image of size 224 * 224 * 3 (RGB image) and FER 2013 dataset is 48 * 48 * 1.

Can you confirm that it is possible to build a simple CNN that achieves more than 70% accuracy on the test set AND within reasonable computing time?

**Comment by jo-eman** [comment]
We are now reaching this project as part of our specialization and coming to the same conclusion.

Also during the audit this "optional" part of the project:

"Optional: (very cool) Hack the CNN. Take a picture for which the prediction of your CNN is Happy. Now, hack the CNN: using the same image SLIGHTLY modified make the CNN predict Sad. "

appears as mandatory and platform ask for reason to fail if you check the "no" box

**Comment by Oumaimafisaoui** [comment]
Hello @jarmo-seljamaa  and  @jo-eman . We made the following corrections:

Accuracy Requirement: The target accuracy has been set at 60%, and this has been consistently reflected in the instructions and audit criteria.

TensorBoard: We’ve ensured alignment between the instructions and audit questions regarding the use of TensorBoard. It remains strongly recommended, and the audit now explicitly requires TensorBoard output.

The use of a Convolutional Neural Network (CNN) is not optional, it is mandatory and central to this project. The CNN is crucial for the emotion classification task, which is the primary objective of this assignment.

CNNs are required because they are particularly effective for image processing tasks, such as facial emotion recognition. This project is designed to provide hands-on experience with CNNs, a key tool in modern computer vision.

**Comment by jarmo-seljamaa** [comment]
Sorry to come back to this with a delay. First of all, thank you for updating the target accuracy. This seems much more achievable now. I think even 65% would have been good, as it would challenge the student a bit more.

However, I'm afraid you misunderstood @jo-eman's question. It is obvious that using CNNs is central to this project and it cannot be done without CNNs. But the task instructions end with an optional extra task:
> Optional: (very cool) Hack the CNN. Take a picture for which the prediction of your CNN is Happy. Now, hack the CNN: using the same image SLIGHTLY modified make the CNN predict Sad. You can find an example on how to achieve this in [this article](https://medium.com/@ageitgey/machine-learning-is-fun-part-8-how-to-intentionally-trick-neural-networks-b55da32b7196)

I believe the problem lies with the [audit, which does not consider this "Hack the CNN" part as optional.](https://github.com/01-edu/public/tree/master/subjects/ai/emotions-detector/audit#hack-the-cnn---guidelines-2). I cannot verify this as I have already graduated and have no access to the platform any more.

Also the audit file seems to have all questions twice. You might want to double check it.
