### ISSUE TITLE
0-shell / job-control / audit [BUG] 

### ISSUE THREAD

**Issue by DIGIX666** [01-edu/public#2456]
**Describe the bug**
<img width="608" alt="SCR-20240223-purh" src="https://github.com/01-edu/public/assets/90353329/e05ef3fd-4379-4172-b53f-07225de6945a">
<img width="460" alt="Screenshot 2024-02-23 at 17 54 06" src="https://github.com/01-edu/public/assets/90353329/92b160bf-7c23-4b83-bcac-6540811f94c4">

Should the audit command be `tar -czf ../home.tar.gz . & jobs` because the command indicate compresses the archive which is itself

**Users**
student : Thox66

**Severity**
⚠️ critical

**Type**
⚙️ functionality

**To Reproduce**

1. `tar -czf home.tar.gz . & jobs`
2. See error

**Workarounds**
Any known workarounds for the issue:
`tar -czf ../home.tar.gz . & jobs`
`tar --exclude='home.tar.gz' -czf ../home.tar.gz . & jobs`

**Expected behavior**
I would like someone to confirm whether this is an error in the audit and correct it to validate the project.

**Desktop (please complete the following information):**

- OS: Sonoma 14.3.1
- Shell: zsh

**Smartphone (please complete the following information):**

- Device: Iphone 13 mini
- OS:  iOS 17.3.1

**Comment by Kevazy** [comment]
Another student here, my interpretation of this audit question is:
1. Run `tar -czf home.tar.gz . &` to put the job in the background (to test your "backgrounding" functionality)
2. Run `jobs` to see your job running the background (to test if your `jobs` command is functioning correctly)
3. Is it being displayed the same way as it does in the standard shell?

The `&` indicates the end of a command and causes it to execute asynchronously (in the background), but I understand the possible confusion in the question.

**Comment by DIGIX666** [comment]
Hi Kévazy,

Thank you for your message.
I had the same first interpretation but I get the same error 
<img width="446" alt="SCR-20240226-qgfh" src="https://github.com/01-edu/public/assets/90353329/b2d38bdc-3bd1-44f2-8ab4-8180af741578">

**Comment by Kevazy** [comment]
Ah, previously I have only been running the shell/command using WSL (Ubuntu) and I noticed from your path you are running Windows. I tried the same with PowerShell and I get the same error, so the question is likely Unix or Linux-specific...

According to [this page](https://softwarerecs.stackexchange.com/questions/25211/linux-like-terminal-for-windows), [Cygwin](https://www.cygwin.com/) seems to be a decent Unix-like terminal for Windows in case you do not feel like going through the hassle of installing WSL on your machine. It should, in theory, use pretty much the same `tar` command as in actual Linux, but haven't tried it myself so no guarantees.

**Comment by Kevazy** [comment]
Hmm, yeah, I am now realizing this is a weirder case than I initially thought. 

Didn't notice it before since it didn't cause any problems on my side, but I am indeed getting this error on Linux, which I guess is similar to yours (in the way that it is trying to read/add itself) but handled differently by the OS as opposed to Mac.
```
❯ tar -czf home.tar.gz .
tar: .: file changed as we read it
```
It goes away the second time you run it, but that's most likely due to it already existing and not being bundled with anything new from the current folder. So basically, the command works "good enough" on Linux, but yeah I do see that you pretty much have to adapt it to your OS when it's being handled differently. Now better understanding the context, your workarounds definitely seem fair enough to pass the audit.

**Comment by DIGIX666** [comment]
I think problem come to my OS (macOS) because I try this command in the shell linux (Ubuntu) and all it's good. I try in other device mac, same problem.

**Comment by zanninso** [comment]
Hello,

Can you confirm that you don't have any file named `home.tar.gz` in the location where you run the command ?

The error occurs due to discrepancies in the implementation of the tar command across different systems. However, the primary objective of the project is not to ensure the flawless execution of the command but rather to ensure that the command is added to the jobs correctly.

**Comment by DIGIX666** [comment]
Hello,

I confirm, I don't have file named `home.tar.gz` before run a command `tar -czf home.tar.gz . &`

<img width="924" alt="SCR-20240325-mdio-3" src="https://github.com/01-edu/public/assets/90353329/be0497ca-95df-406f-a57c-8a5964bf48dd">

**Comment by zanninso** [comment]
Okay thanks for you feedback, This will be fixed

**Comment by DIGIX666** [comment]
No problem ;)

When it's fixed can you please ping me
