### ISSUE TITLE
using-map subject

### ISSUE THREAD

**Issue by liinabakhoff** [01-edu/public#2480]
using-map
---
Please separate subtasks into different exercises. It is both very demotivating and difficult to test and debug so many functions in one exercise.

**Comment by nprimo** [comment]
Hi @liinabakhoff, thank you for your feedback. Could you please elaborate a bit more on the difficulty you're facing? The exercise requires indeed to submit several functions but they're all quite limited in their scope and their objective is well defined. 

To test your solution, you can use the provided examples and think about some additional cases as well. You can `console.log` the result of your functions or use a JS framework ([jest](https://jestjs.io/) or [mocha](https://mochajs.org/) for example) to better understand what's going on, but you should be used to this type of tools since it's not the first quest on this piscine :)

**Comment by nprimo** [comment]
@liinabakhoff feel free to comment on this issue if you would like to give us some idea on what should be a better a way to split this exercise :)
