### ISSUE TITLE
[FEATURE] 01-EDU blockchain- degree / diploma / course issuance 

### ISSUE THREAD

**Issue by SomaSapien** [01-edu/public#2532]
**PROBLEM STATEMENT**
This is not a "problem" per se, but more of a deficiency.

At the moment, there does not seem to be a clear and unifying accreditation standard between all 01-EDU schools, ie. the final accreditation rests almost solely on the partnering organisation for the school using the 01-EDU platform. For example, the grit:lab accreditation is linked primarily to "Ålands Yrkes Gymnasium", a vocational college / school here on Åland.

This means that graduating students are not able to leverage the reputation / credibility that 01-EDU is slowly building in the marketplace (both through its own efforts, as well as the possible success of its alumni). ie. Despite the 01-EDU platform being used globally, in Europe, Asia, Africa etc. etc., there is no common or unifying standard / symbology in the final certificates issued. 

**TYPE**
(⚙️ functionality) & (🔐 security)

**EXPECTED BENEFIT**
Added worth and visibility when graduating from an 01-EDU-affiliated coding school.

**TARGET AUDIENCE**
Beneficiaries are:
- All students / alumni of 01-EDU-affiliated schools,

... whilst target "users" are:
- Stakeholders in industry / potential employers 

**SOLUTION**
Implementation of a private-blockchain for degree / diploma issuance, that is in some way integrated into the certificate given by the 01-EDU-affiliated school. This will not only make it clear that 01-EDU is involved in the school's program design (1. credibility), it will also prevent fraud and allow anyone to verify that the certificate is authentic (2. security), whilst finally implementing {drumroll, with faint cowbells in the background...}: a technology that 01-EDU not only provides education for, but that is likely to be front-and-centre for the foreseeable future regarding web3, finance etc. etc. (3. "razmatazz").

**ALTERNATIVES CONSIDERED**
I honestly haven't looked into more traditional alternatives in-depth, as they almost always involve increased administrative overhead & workload for all organisations involved (whilst in no way using 'tech').

**ADDITIONAL COMMENTS**
The resulting fame and general adoration that may come the way of anyone who manages to implement all the above, may just be too much for one person to bear... so, if this solution is rubber-stamped and given the "go-ahead", perhaps it would be best that a team of coders is assigned the task so that the resulting workload of flying around the world giving key-note speeches and interviews, can be handled by several people.

**Comment by kigiri** [comment]
Hello @SomaSapien and thank you for the detailled issue.

My answer may lack the same level of completeness, but the problem is a bit more complex than it may appear at first glance.

Not all our schools are following the same curriculum, as such making a "standard" `01-edu` certification would be a bit difficult without enforcing serious restrictions on the current modularity most our clients want.

We could do a school by school based certificate, actually some of our schools already have a gouvernemental accreditation to deliver a diplomas but as you put it yourself it adds quite a bit of administrative load on them.

About using blockchain for it, really no value in our case, what ever we choose to provide a certificate we would have to be a third party to be trusted so... Blockchain also make it harder to invalidate certificate if one would be given by mistake or cheating was detected later on. Overall we fail to see the added value over complexity & limitation of the blockchain in a case where trust & centralisation are no issue. I do admit we didn't put that much thought into potential benefits of the blockchain here just failed to see a good fit for our need.

One thing we did plan to do in the future is to allow every students to have a customisable public profile where you could choose to show some or all of the projects you did and level reached in modules / piscines.

Our hope is that we can make this profile a valid reputation proof that would be as unified as possible form our schools, without loosing the curriculum context and the potential differences.
