### ISSUE TITLE
[BUG] `iterativefactorial` subject

### ISSUE THREAD

**Issue by isaacid** [01-edu/public#2691]
iterativefactorial
---
package piscine

func IterativeFactorial(nb int) int {
	if nb < 0 {
		return 0
	} else if nb == 0 {
		return 1
	} else {
		result := 1
		for i := nb; i > 0; i-- {
			result *= i
		}
		return result
	}
}
Being told that I'm creating an infinite loop

**Comment by Wizard254** [comment]
Before getting into the actual problem, let's first get you up and running with [Including code in Github Issues with Markdown](https://github.github.com/gfm/#fenced-code-blocks). That should fix your badly formatted code here in Github issues.

Your problem is an implementation detail, be sure to read the instructions again. 
Just an insight to where your problem might be, read this to know deeper about [factorial](https://en.wikipedia.org/wiki/170_(number)#:~:text=170%20is%20the%20largest%20integer,%3D%207.25741562%20%C3%97%2010306.) and most probably this [math.MaxInt](https://stackoverflow.com/a/6878625)

**Comment by Wizard254** [comment]
@HarryVasanth This is definitely not a `bug`. Should have probably been marked `won't fix` and closed, because it's a challenge to get the students to think out of the box, and fix their code. 

> This stems from: 🎭 Our Philosophy
> Some of our subjects are intentionally designed to be ambiguous or less specific, reflecting our unique pedagogical approach.
