### ISSUE TITLE
[QUESTION] drawing subject

### ISSUE THREAD

**Issue by sahmedG** [01-edu/public#2743]
drawing
---
let rectangle = gs::Rectangle::new(&gs::Point::new(150, 150), &gs::Point::new(50, 50));
    rectangle.draw(&mut image);
X,Y end point are equal resulting in equal length and width generating a square instead of rectangle.

**Comment by zanninso** [comment]
> ## drawing
> let rectangle = gs::Rectangle::new(&gs::Point::new(150, 150), &gs::Point::new(50, 50)); rectangle.draw(&mut image); X,Y end point are equal resulting in equal length and width generating a square instead of rectangle.

Hello  @sahmedG from the given example its clearly will draw a square because of the distances between the X,Y are equal!
I see no problem in the given example if you can provide more examples or clarify more you error it will be good otherwise I will close this issue if everything is clear for you
Thank you.
