### ISSUE TITLE
printnbr subject

### ISSUE THREAD

**Issue by Bekansm** [01-edu/public#486]
printnbr
---
This exercise is marked as optional, but in 1 exercise (foreach) of Quest 9 it's needed to submit a code. Please remark it as required or change exercise in Quest 9
TY

**Comment by LEEDASILVA** [comment]
sorry i'm not understanding the question, you assign with the comment "printnbr subject" but speak about foreach.  
Should the exercise printnbr be optional on the quest 9? or is it repeated on the quest 9? or is the exercise foreach repeated?

**Comment by Frenchris** [comment]
Hello @Bekansm 

Sorry we had to reread several times to understand what we thought you meant the issue was. 

The exercise forEach does use the function printNbr as an example. 
That printNbr function in the example could be easily replaced with a fmt.PrintLn()

When we give examples inside a subject we are "guiding" the student. The student has to figure it out somehow. 
In order to submit a working forEach function, you **do not need** to have a working printNbr in your repo. 

Hence, we will not change this exercise to required in quest2, nor we will change the exercise forEach in quest 9.

At this point in the piscine we expect students to be able to start to "debug" a program. Consider this as a part of the pedagogy.

Sincerely,

Chris
