### ISSUE TITLE
isprime subject

### ISSUE THREAD

**Issue by GDansen** [01-edu/public#803]
isprime
---
Program wants the value 1 to return false, but 1 is a prime number

**Comment by Frenchris** [comment]
1 is a special case and there is a whole debate around it.

-Why some people say it's prime: Its positive divisors are 1 and itself.
-Why some people say it's not prime: It doesn't have exactly two positive divisors.

Here is a whole article which gives the arguments why it is not. 
https://blogs.scientificamerican.com/roots-of-unity/why-isnt-1-a-prime-number/

From a pedalogical point of view. We decided to go with that view because it is also a good example of handling an exception.

I added a line to the subject specifying this consideration.
Thank you for your feedback.
