### ISSUE TITLE
ascii-art-web hrefs are not redirecting correctly

### ISSUE THREAD

**Issue by Gervin1** [01-edu/public#832]
ascii-art-web hrefs are not redirecting correctly, it redirects to raw file instead of src.
---
Not working hrefs: 

Ascii-art-web consists in creating and running a server, in which it will be possible to use a web **GUI** (graphical user interface) version of your last project, [ascii-art](../ascii-art).

Your webpage must allow the use of different [banners](../ascii-art).

**Comment by Frenchris** [comment]
additonal info : "In task ascii-art-web there is a href to git repo as "../ascii-art", but it redirects them as raw so they get 404 because it can't read raw repository ".
@LEEDASILVA @OGordoo @MSilva95 I cannot find the PR that fixed all links like these. Could it be possible that since the public repo is now mirrored directly on the school server, a global change needs to be done?

**Comment by LEEDASILVA** [comment]
yes i will push the fix
