### ISSUE TITLE
[Audit Message] - After reducing number of required auditors

### ISSUE THREAD

**Issue by nik-don** [01-edu/public#888]
**Describe the bug**
I believe this message (highlighted in pink) occurs when reducing the number of auditors required.

**To Reproduce**
- Pass project with required audits
- Auditors Required changed from 5 to 3

**Expected behavior**
Should not display the message being displayed currently

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/93073558/141195389-28a14fdb-0c24-495e-aaed-d6044b33894b.jpg)

**Type**
Add the correct label to your bug report : blocking, major, minor
minor

**Priority**
Add the correct label to your bug report : high, normal, low
normal

**Subject**
Add the correct labels to your bug report : onboarding, toad, admin, intra, design
intra

**Comment by Frenchris** [comment]
Not technically a bug. When a student get a batch of 5 required audits and that the project required audits are changed to another number. The attribution of this new number audits only happens when resubmitting for audits. The platform does not cancel an in progress batch of audits in order to not penalized auditors that were already assigned. Working as intended.

**Comment by Frenchris** [comment]
Not technically a bug. When a student get a batch of 5 required audits and that the project required audits are changed to another number. The attribution of this new number audits only happens when resubmitting for audits. The platform does not cancel an in progress batch of audits in order to not penalized auditors that were already assigned. Working as intended.
