### ISSUE TITLE
atm-management-system subject

### ISSUE THREAD

**Issue by KamalZ18** [01-edu/public#899]
atm-management-system
---
• ATM Management System → Propose a change:
RDBMS → Relational Database Management System;

Currently the Program Specification → Database does NOT conform to the rules of a Relational Database;
the 2 DB Files: users.txt and records.txt are the Database;****

• In order to make the Database a Relational Database, the following changes need to be implemented.

• The Users.txt file should have 5 fields:
Customer ID which is a unique key which identifies the User (Customer),
Full name (first & last name), password, and phone number;
Country (location of User/Customer; e.g England, Spain, France or Portugal),
The Customer ID is the Key field.

• The Records.txt (transactions) file should have 5 fields:
date of creation (timestamp),
Customer ID (from the Users file, which identifies the User (Customer)),
amount (+ve for deposits, -ve for withdrawals), balance, type of account (current OR savings OR fixed interest, etc.);
date of creation (timestamp) is the Key field.

• I recommend this Change, because it would make the System more efficient,
it would make the Database a relational database, which is more efficient.

**Comment by MSilva95** [comment]
We will take a look at your suggestions, thank you for your feedback

**Comment by KamalZ18** [comment]
Hi there,
thank you for considering my suggestions;

• Also the Customer ID and Account ID needs to be generated by the System (the software);
not entered by the User.

• The Customer ID and Account ID have to be unique.

**Comment by MSilva95** [comment]
@LEEDASILVA Is checking your suggestions

**Comment by LEEDASILVA** [comment]
Hey @KamalZ18 sorry for taking to long to answer this issue. So we can add some of the proposals:

- Relational Database can be added for it to be more efficient yes. But i feel like it can be a bit hard for some of the students to do. This is one of the first open projects. The first time the student use Relation Database is on the project [`forum`](https://public.01-edu.org/subjects/forum/#sqlite) witch is more advance. 
- If we add the Relational Database we can just remove the files and add a simple DB like `sqlite`. But like i sad maybe it can be to difficult since they did not used it yet. (add the first time some students are going to use C)

What i propose : 

- is to add it as bonus, where students can adapt it to be a relation database (create their own sqlite database with the right relations)
- add some specifics on the files like IDs. for users and records.

@KamalZ18 what do you think?

**Comment by KamalZ18** [comment]
Hi to @LEEDASILVA ,

Happy New Year to Leeda;

sorry for taking to long to respond to your proposal;

**yes I agree with you:**

•  add it (SQL Relational Database) as a Bonus,
  were students can adapt it to be a SQL relation database
  (create their own Sqlite database with the correct relations)

AND

•  add some specifics on the files like IDs for users and records:
Both the Customer ID and Account ID must be generated by the System (the code).

thank you,
regards,
Kamal H. Zada BSc.

**Comment by LEEDASILVA** [comment]
Hey i will create the PR today

**Comment by MSilva95** [comment]
Hello @KamalZ18! You can take a look at the PR @LEEDASILVA  has done and leave your feedback in it if you like.
Thank You for your help!
