### ISSUE TITLE
ascii-art-web-stylize subject

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#903]
ascii-art-web-stylize
---
The audit contains two questions about test file:
```
Is there a test file for this code?
Are the tests checking each possible case?
```
Is it even possible to have a test file that can be run on a web site to test the style of the interface?

**Comment by jarmo-seljamaa** [comment]
Why did you close this issue? There are no changes to the audit questions so far. Can we at least have an answer here?

**Comment by Gervin1** [comment]
@MSilva95 Could you explain why this was closed?

**Comment by MSilva95** [comment]
Hello @jarmo-seljamaa! 
I apologize for inconvenience, a PR was done and it will be merged today, normally after the pr is done we closed the issue, but from now on we will leave the issue open until the pr is merged and we will link the issue in the pr so that it is possible to see what was changed.
