### ISSUE TITLE
forum-security misleading info

### ISSUE THREAD

**Issue by GermanKarK** [01-edu/public#905]
Students wrote about some misleading info with the forum project which are shown in the screenshots
![forum-security_1](https://user-images.githubusercontent.com/95408096/145812156-7c233af4-a381-4894-ac9f-a96ed558ba9e.png)
![forum-security_2](https://user-images.githubusercontent.com/95408096/145812167-a7ca765c-9e0b-4438-a271-86ba3565ad36.png)

**Comment by LEEDASILVA** [comment]
@GermanKarK thank you for the feedback.
session and cookies are to be implemented in the mandatory project. But not tested in a secure way! (in the audit) So this repetition of session and cookies is so that students can actually see that there are possibilities for attacks and correct them in this project.

The password encryption is repeated  as well because it is not tested in the audit. This project would insure the encryption.

`- It is recommended that the code should present a **test file**.`-> the phrase is not well formed i will correct it. But in programing it is very very important that test are made. Testing is any activity aimed at evaluating an attribute or capability of a program or system and determining that it meets its required results. So students must do a test files

is it clear?

**Comment by uristdwarf** [comment]
Hey, I'm the author that image.
I agree that cookies and sessions can be implemented in a bad way, however the main project's description already strongly advises you to implement these, so I guess it would be better if it doesn't and later in security this is introduced?

As for testing, I'm assuming you mean unit testing? In this case it could be something like "Is the code covered by [unit tests](https://go.dev/doc/tutorial/add-a-test)?" or something like that

The cipher suites are indeed already provided by most HTTPS certificates and CA's, which is why I find them confusing. Do we need to choose cipher suites the client can use, or are the default fine?

**Comment by LEEDASILVA** [comment]
I do not know if the best option is to remove the session & cookies from the main subject. But maybe we could add it was a bonus, so students can decide if they do it or not. And when arriving to security the students must do it in the right way. what do you think?

Yes, unit tests (for the server side), should have been more clear on this one. **But will add the specifications**

For the cipher suites, the default are fine but the idea is for students to search and know about them!
for example you can use the `tls.Config` and enable the `PreferServerCipherSuites` -> this causes server to use Go's default cipher suites preferences, which are tuned to avoid attacks.

**Comment by uristdwarf** [comment]
I think that securing cookies/sessions/passwords could be indeed bonus tasks. although I think sessions will still need to be implemented (even if insecure) in the main project

Thank you for making this clear. This has been bugging a lot of other students about how you're supposed to test (other than manually) websites.

`PreferServerCipherSuites` is deprecated, but I do get your point. The cipher suites should be some way relevant when implementing HTTPS.

**Comment by LEEDASILVA** [comment]
ok nice :+1: i will tag the PR here <https://github.com/01-edu/public/pull/907> any other feedback will be welcome

**Comment by tallestbassist** [comment]
Regarding the password hashing i would suggest keep the forum as it is(maybe just add a checkpoint into audit that password is hashed in sql database?). So you would only use the bcrypt library to just hash the password and thats it . But it the security part you would have to add pepper/salt to that hashing part.

**Comment by uristdwarf** [comment]
> But it the security part you would have to add pepper/salt to that hashing part.
bcrypt (and the library) already adds salt though.
https://en.wikipedia.org/wiki/Bcrypt
