### ISSUE TITLE
groupie-tracker: What is an event?

### ISSUE THREAD

**Issue by uristdwarf** [01-edu/public#908]
The description on events is confusing and there's a lot of interpretation going around in my school on what is meant by events:

- Is it some JavaScript code that triggers on an event?
- Is it something the client sends to the server and back (using [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events))?
- Is it some kind of CSS effect?

If it's the first two, then you would need to implement some kind of JavaScript, which is infuriating to some people because the Javascript piscine is still months away, which is supposed to teach us the basics (In other words, we'd have to learn some JavaScript before the piscine).

If it's the third, then you could basically create a static website without needing any user input (and hence you don't need to send any 400 error, which is required to be implemented) and this is what my team personally did.

A concrete example on what an event system should look like would help dispel some of these interpretations.

**Comment by MSilva95** [comment]
hello @uristdwarf! You can take a look here https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events
This link is in the task, and explains what are events

**Comment by uristdwarf** [comment]
Sorry for taking so long to response, had to read through the link you gave (though I already read it) just to be on the same page).

So it's my first point, in that it's JavaScript code, then? Can you please answer me why are we supposed to learn some JavaScript (even if it's very little) before the JavaScript piscine (which is supposed to teach us the basics of JavaScript, if I understand correctly?).

It would be like if we were (during the first piscine and first few months) programming in JavaScript, and then suddenly we had to setup a basic go server to serve dynamic HTML. Probably not hard, but quite illogical.

**Comment by uristdwarf** [comment]
There's also the issue that the application doesn't need to contact the server other than to get pretty much static files. So there's really no place to implement the 400 error reasonably as asked in the audit.

**Comment by Gervin1** [comment]
@MSilva95 Could you respond?

**Comment by LEEDASILVA** [comment]
hey @uristdwarf, firstly for the event situation:
- In this project the event we want you to do is better known as a client call to the server ([client - server] (https://en.wikipedia.org/wiki/Request%E2%80%93response)). Maybe the reason for this confusion is because we want you to be able to freely choose how you want to create the event | action. 

**example:** you can create pages for all the information. Where you click on a button for the next page. Or submission of a form

**solution**:  we can explain this part better. What do you think?

for the 400 error **Bad request** it is a bit tricky, i do think you are right so we could remove it.
@MSilva95 will do the PR with all the fixes
