### ISSUE TITLE
manipulate-values subject

### ISSUE THREAD

**Issue by Rostislav-chi** [01-edu/public#932]
manipulate-values
---
The task needs a lot of additional explanations.
Need to specify, what values should each function receive and what should it return. 
For example, filter receives an array as last argument, but you check it as first argument.
Also does it have to return an object with objects or an array with objects?
Also, should the callback function receive 3 arguments (element, index and array), or only one element? 
If one - then which one - key or value or key-value pair as an array?
Also it is not stated, if we can use the Array.filter, .map and .reduce methods.
Also need an example of what is expected! That is crucial for all the tasks!!!
The same is concerning manipulate-keys and manipulate-entries

**Comment by MSilva95** [comment]
hello @Rostislav-chi!
@LEEDASILVA  will take a look at those exercises, thank you for your feedback!

**Comment by LEEDASILVA** [comment]
hey @Rostislav-chi  so i took a look at the exercise. One thing i don't understand when you say :

>  If one - then which one - key or value or key-value pair as an array?

because the name of the exercise is manipulate-**values** which means that the element passed to the functions is the value. Same goes for the others, manipulate-**key** and manipulate-**entries**. 

>  Also it is not stated, if we can use the Array.filter, .map and .reduce methods

if it is not stated means that you can use them

>  Also does it have to return an object with objects or an array with objects?

it returns an object for map and filter. The `filterValue` and `mapValue` is to do the same as in the methods from array (`map`, `filter`) but for objects

>  Also need an example of what is expected! That is crucial for all the tasks!!!

we did not add examples because we direct you to Notions, like <https://devdocs.io/javascript/global_objects/array/filter> which already as examples.

but i will add the examples.

**Comment by LEEDASILVA** [comment]
The PR is made let me know what you think
